/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.VaccineManufacturerWorkArea;

import java.awt.CardLayout;

/**
 *
 * @author pradnyalgandhi
 */
public class VaccineManufacturerAdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form VaccineManufacturerAdminJPanel
     */
    public VaccineManufacturerAdminJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOrder = new javax.swing.JButton();
        lblManufacturereAdmin = new javax.swing.JLabel();
        btnInventory = new javax.swing.JButton();
        btnDeliveryManager = new javax.swing.JButton();

        btnOrder.setText("Manage Orders");
        btnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderActionPerformed(evt);
            }
        });

        lblManufacturereAdmin.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblManufacturereAdmin.setForeground(new java.awt.Color(204, 204, 204));
        lblManufacturereAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblManufacturereAdmin.setText("Welcome, Manufacturer Admin");

        btnInventory.setText("Manage Inventory");
        btnInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventoryActionPerformed(evt);
            }
        });

        btnDeliveryManager.setText("Manage Delivery Manager");
        btnDeliveryManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeliveryManagerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblManufacturereAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(379, 379, 379)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDeliveryManager, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnInventory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(lblManufacturereAdmin)
                .addGap(57, 57, 57)
                .addComponent(btnOrder)
                .addGap(18, 18, 18)
                .addComponent(btnInventory)
                .addGap(18, 18, 18)
                .addComponent(btnDeliveryManager)
                .addContainerGap(560, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderActionPerformed
       ManageOrdersJPanel manageOrdersJPanel = new ManageOrdersJPanel( mainWorkArea, enterprise);
       mainWorkArea.add("manageOrdersJPanel", manageOrdersJPanel);
       CardLayout layout = (CardLayout)  mainWorkArea.getLayout();
       layout.next( mainWorkArea);
    }//GEN-LAST:event_btnOrderActionPerformed

    private void btnInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventoryActionPerformed
       ManageInventoryJPanel manageInventoryJPanel = new ManageInventoryJPanel( mainWorkArea, enterprise);
       mainWorkArea.add("manageInventoryJPanel", manageInventoryJPanel);
       CardLayout layout = (CardLayout)  mainWorkArea.getLayout();
       layout.next( mainWorkArea);
    }//GEN-LAST:event_btnInventoryActionPerformed

    private void btnDeliveryManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeliveryManagerActionPerformed
       ManageDeliveryManagerJPanel manageDeliveryManagerJPanel = new ManageDeliveryManagerJPanel( mainWorkArea, enterprise);
       mainWorkArea.add("manageDeliveryManagerJPanel", manageDeliveryManagerJPanel);
       CardLayout layout = (CardLayout)  mainWorkArea.getLayout();
       layout.next( mainWorkArea);
    }//GEN-LAST:event_btnDeliveryManagerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeliveryManager;
    private javax.swing.JButton btnInventory;
    private javax.swing.JButton btnOrder;
    private javax.swing.JLabel lblManufacturereAdmin;
    // End of variables declaration//GEN-END:variables
}
