/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.SystemAdminWorkArea;

import Business.EcoSystem;
import Business.Person.Person;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.awt.Component;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pradnyalgandhi
 */
public class ManagePersonJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MainPersonJPanel
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    public ManagePersonJPanel(JPanel userProcessContainer, EcoSystem ecosystem) {
        initComponents();
        this.ecosystem = ecosystem;
        this.userProcessContainer = userProcessContainer;

        populatePersonTable();
        btnUpdate.setEnabled(false);
        btnDelete.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPhone = new javax.swing.JTextField();
        lblStreet = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        txtZipcode = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        lblApartment = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtCommunity = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        lblCommunity = new javax.swing.JLabel();
        btnView = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();
        lblManagePerson = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        personTable = new javax.swing.JTable();
        txtStreet = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        txtID = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        lblID = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        lblAge = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setBackground(new java.awt.Color(167, 199, 231));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPhone.setBackground(new java.awt.Color(214, 229, 244));
        add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 570, 212, -1));

        lblStreet.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblStreet.setForeground(new java.awt.Color(0, 0, 0));
        lblStreet.setText("Street:");
        add(lblStreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 460, -1, -1));

        lblPhone.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblPhone.setForeground(new java.awt.Color(0, 0, 0));
        lblPhone.setText("Phone No:");
        add(lblPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 570, -1, -1));

        txtZipcode.setBackground(new java.awt.Color(214, 229, 244));
        add(txtZipcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 490, 212, -1));

        txtEmail.setBackground(new java.awt.Color(214, 229, 244));
        add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 610, 212, -1));

        lblApartment.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblApartment.setForeground(new java.awt.Color(0, 0, 0));
        lblApartment.setText("Zip Code:");
        add(lblApartment, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 500, -1, -1));

        lblEmail.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(0, 0, 0));
        lblEmail.setText("Email:");
        add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 610, -1, -1));

        txtCommunity.setBackground(new java.awt.Color(214, 229, 244));
        add(txtCommunity, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 650, 212, -1));

        btnUpdate.setBackground(new java.awt.Color(0, 0, 0));
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 710, -1, -1));

        lblCommunity.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblCommunity.setForeground(new java.awt.Color(0, 0, 0));
        lblCommunity.setText("Community:");
        add(lblCommunity, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 650, -1, -1));

        btnView.setBackground(new java.awt.Color(0, 0, 0));
        btnView.setForeground(new java.awt.Color(255, 255, 255));
        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        add(btnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 340, -1, -1));

        btnCreate.setBackground(new java.awt.Color(0, 0, 0));
        btnCreate.setForeground(new java.awt.Color(255, 255, 255));
        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 710, -1, -1));

        lblManagePerson.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblManagePerson.setForeground(new java.awt.Color(0, 0, 0));
        lblManagePerson.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblManagePerson.setText("MANAGE PERSON");
        add(lblManagePerson, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 62, 880, -1));

        lblName.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblName.setForeground(new java.awt.Color(0, 0, 0));
        lblName.setText("Name:");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 410, -1, -1));

        personTable.setBackground(new java.awt.Color(214, 229, 244));
        personTable.setForeground(new java.awt.Color(0, 0, 0));
        personTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "ID", "Street", "Zipcode", "Age", "Community", "Phone No", "Email"
            }
        ));
        jScrollPane1.setViewportView(personTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 129, 980, 183));

        txtStreet.setBackground(new java.awt.Color(214, 229, 244));
        add(txtStreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 450, 212, -1));

        btnDelete.setBackground(new java.awt.Color(0, 0, 0));
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 340, -1, -1));

        txtID.setBackground(new java.awt.Color(214, 229, 244));
        add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 370, 212, -1));

        txtName.setBackground(new java.awt.Color(214, 229, 244));
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 410, 212, -1));

        lblID.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblID.setForeground(new java.awt.Color(0, 0, 0));
        lblID.setText("ID:");
        add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 370, -1, -1));

        txtAge.setBackground(new java.awt.Color(214, 229, 244));
        add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 530, 212, -1));

        lblAge.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblAge.setForeground(new java.awt.Color(0, 0, 0));
        lblAge.setText("Age:");
        add(lblAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 530, -1, -1));

        btnBack.setBackground(new java.awt.Color(0, 0, 0));
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, -1, -1));

        btnCancel.setBackground(new java.awt.Color(0, 0, 0));
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 710, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        int ID = Integer.parseInt(txtID.getText());
        String name = txtName.getText();
        String street = txtStreet.getText();
        String zipcode = txtZipcode.getText();
        int age = Integer.parseInt(txtAge.getText());
        String community = txtCommunity.getText();
        String phoneNo = txtPhone.getText();
        String email = txtEmail.getText();

        if (txtID.getText().isEmpty() || txtAge.getText().isEmpty() || name.isEmpty() || street.isEmpty() || zipcode.isEmpty() || community.isEmpty() || phoneNo.isEmpty() || email.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Empty Fields", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        else if (phoneNo.length() != 10) {
            JOptionPane.showMessageDialog(null, "Invalid Phone Number", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        else if (validateEmail(email) == false) {
            JOptionPane.showMessageDialog(null, "Invalid Email", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else if (zipcode.length() != 5) {
            JOptionPane.showMessageDialog(null, "Invalid Zipcode", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        else if(!ecosystem.getPersonDirectory().checkIfIDIsUnique(ID)){
            JOptionPane.showMessageDialog(null, String.format("Person ID %s already exists!", ID),"Warning",JOptionPane.ERROR_MESSAGE);
        }
        else if(!ecosystem.getPersonDirectory().checkIfNameIsUnique(name)){
            JOptionPane.showMessageDialog(null, String.format("Person name %s already exists!", name),"Warning",JOptionPane.ERROR_MESSAGE);
        }
        else if(!ecosystem.getPersonDirectory().checkIfEmailIsUnique(email)){
            JOptionPane.showMessageDialog(null, String.format("Person email %s already exists!", email),"Warning",JOptionPane.ERROR_MESSAGE);
        }
        else{
            ecosystem.getPersonDirectory().newPerson(ID, name, street, zipcode, age, community, phoneNo, email);
            populatePersonTable();
            JOptionPane.showMessageDialog(null, "Customer Created");
        }
        
//        System.out.println(ecosystem.getPersonDirectory().getPersonList());

        txtID.setText("");
        txtName.setText("");
        txtStreet.setText("");
        txtZipcode.setText("");
        txtAge.setText("");
        txtPhone.setText("");
        txtEmail.setText("");
        txtCommunity.setText("");

    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = personTable.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a Row");
        } else {
            btnUpdate.setEnabled(true);
            btnDelete.setEnabled(true);
            txtID.setEnabled(false);
            DefaultTableModel model = (DefaultTableModel) personTable.getModel();
//            UserAccount selectedUser = (UserAccount) model.getValueAt(selectedRow, 0);
            Person selectedPerson = (Person) model.getValueAt(selectedRow, 0);
            txtID.setText(String.valueOf(selectedPerson.getPersonID()));
            txtName.setText(selectedPerson.getName());
            txtStreet.setText(selectedPerson.getStreet());
            txtZipcode.setText(selectedPerson.getZipcode());
            txtAge.setText(String.valueOf(selectedPerson.getAge()));
            txtPhone.setText(String.valueOf(selectedPerson.getPhoneNo()));
            txtEmail.setText(selectedPerson.getEmail());
            txtCommunity.setText(selectedPerson.getCommunity());

        }
        
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = personTable.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a Row");
        } else {
            btnDelete.setEnabled(false);
            btnUpdate.setEnabled(false);
            
            DefaultTableModel model = (DefaultTableModel) personTable.getModel();
            Person selectedPerson = (Person) model.getValueAt(selectedRow, 0);

            ecosystem.getPersonDirectory().deletePerson(selectedPerson);

            populatePersonTable();
            
            txtID.setText("");
            txtName.setText("");
            txtStreet.setText("");
            txtZipcode.setText("");
            txtAge.setText("");
            txtPhone.setText("");
            txtEmail.setText("");
            txtCommunity.setText("");
            txtID.setEnabled(true);
    }//GEN-LAST:event_btnDeleteActionPerformed
    }
    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        txtID.setEnabled(false);
        int ID = Integer.parseInt(txtID.getText());
        String name = txtName.getText();
        String street = txtStreet.getText();
        String zipcode = txtZipcode.getText();
        int age = Integer.parseInt(txtAge.getText());
        String community = txtCommunity.getText();
        String phoneNo = txtPhone.getText();
        String email = txtEmail.getText();
        
        int selectedRow = personTable.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(this, "Please select a Row");
            txtID.setEnabled(true);
        }
        else{
            btnDelete.setEnabled(false);
            btnUpdate.setEnabled(false);
            DefaultTableModel model = (DefaultTableModel) personTable.getModel();
            Person person = (Person)model.getValueAt(selectedRow, 0);
            
            if (txtID.getText().isEmpty() || txtAge.getText().isEmpty() || name.isEmpty() || street.isEmpty() || zipcode.isEmpty() || community.isEmpty() || phoneNo.isEmpty() || email.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Empty Fields", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        else if (phoneNo.length() != 10) {
            JOptionPane.showMessageDialog(null, "Invalid Phone Number", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        else if (validateEmail(email) == false) {
            JOptionPane.showMessageDialog(null, "Invalid Email", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else if (zipcode.length() != 5) {
            JOptionPane.showMessageDialog(null, "Invalid Zipcode", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
             
        
            else{
            ecosystem.getPersonDirectory().updatePerson(person, name, street, zipcode, age, community, phoneNo, email);
//            System.out.print(username);
            JOptionPane.showMessageDialog(this, " Person updated successfully");
            populatePersonTable();
            txtID.setText("");
            txtName.setText("");
            txtStreet.setText("");
            txtZipcode.setText("");
            txtAge.setText("");
            txtPhone.setText("");
            txtEmail.setText("");
            txtCommunity.setText("");
            txtID.setEnabled(true);
        }
            
        }
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        SystemAdminWorkAreaJPanel sysAdminwjp = (SystemAdminWorkAreaJPanel) component;
        //        sysAdminwjp.populateTree();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        txtID.setEnabled(true);
        btnUpdate.setEnabled(false);
        btnDelete.setEnabled(false);
        txtID.setText("");
        txtName.setText("");
        txtStreet.setText("");
        txtZipcode.setText("");
        txtAge.setText("");
        txtPhone.setText("");
        txtEmail.setText("");
        txtCommunity.setText("");
    }//GEN-LAST:event_btnCancelActionPerformed


    private boolean validateEmail(String email) {
        Pattern p = Pattern.compile("^[a-zA-z0-9]+@[a-zA-Z0-9]+.[a-zA-Z0-9]+$");
        Matcher m = p.matcher(email);
        return m.matches();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnView;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblApartment;
    private javax.swing.JLabel lblCommunity;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblManagePerson;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblStreet;
    private javax.swing.JTable personTable;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtCommunity;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtStreet;
    private javax.swing.JTextField txtZipcode;
    // End of variables declaration//GEN-END:variables

    private void populatePersonTable() {

        DefaultTableModel dtm = (DefaultTableModel) personTable.getModel();
        dtm.setRowCount(0);

        for (Person person : ecosystem.getPersonDirectory().getPersonList()) {
//            System.out.println(person);
            Object[] row = new Object[8];
            row[0] = person;
            row[1] = person.getPersonID();
            row[2] = person.getStreet();
            row[3] = person.getZipcode();
            row[4] = person.getAge();
            row[5] = person.getCommunity();
            row[6] = person.getPhoneNo();
            row[7] = person.getEmail();

            dtm.addRow(row);

        }

    }
}
