/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.City.City;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;

import Business.Organization.Organization;
import Business.Person.Person;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot3D;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author MyPC1
 */
public class SystemAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdminWorkAreaJPanel
     */
    JPanel userProcessContainer;
    EcoSystem system;
    UserAccount userAccount;
    City city;
    Organization organization;
    Enterprise enterprise;

    public SystemAdminWorkAreaJPanel(JPanel userProcessContainer, City city, UserAccount userAccount, Organization organization,
            Enterprise enterprise, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        this.city = city;
        this.organization = organization;
        populateTree();

    }
        
    
    public void populateTree(){
        DefaultTreeModel model=(DefaultTreeModel)jTree.getModel();
        ArrayList<City> networkList=system.getCityList();
        ArrayList<Enterprise> enterpriseList;
        ArrayList<Organization> organizationList;

        City city;
        Enterprise enterprise;
        Organization organization;

        DefaultMutableTreeNode networks=new DefaultMutableTreeNode("Networks");
        DefaultMutableTreeNode root=(DefaultMutableTreeNode)model.getRoot();
        root.removeAllChildren();
        root.insert(networks, 0);

        DefaultMutableTreeNode networkNode;
        DefaultMutableTreeNode enterpriseNode;
        DefaultMutableTreeNode organizationNode;

        int i = 0;
        for(City n : system.getCityList()){
            networkNode = new DefaultMutableTreeNode(n.getName());
            networks.insert(networkNode, i);
            i++;
            int j = 0;
            for(Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()){
                enterpriseNode = new DefaultMutableTreeNode(e.getName());
                networkNode.insert(enterpriseNode, j);
                j++;
                int k = 0;
                for(Organization o : e.getOrganizationDirectory().getOrganizationList()){
                    organizationNode = new DefaultMutableTreeNode(o.getName());
                    enterpriseNode.insert(organizationNode, k);
                    k++;
                }
            }
        }
        model.reload();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void jTreeValueChanged(javax.swing.event.TreeSelectionEvent evt) {

    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnManageCity = new javax.swing.JButton();
        btnManageEnterprise = new javax.swing.JButton();
        btnCovid = new javax.swing.JButton();
        btnManageEnterpriseAdmins = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree = new javax.swing.JTree();
        btnManagePerson1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(167, 199, 231));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnManageCity.setBackground(new java.awt.Color(0, 0, 0));
        btnManageCity.setForeground(new java.awt.Color(255, 255, 255));
        btnManageCity.setText("Manage City");
        btnManageCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageCityActionPerformed(evt);
            }
        });
        add(btnManageCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 253, 190, 30));

        btnManageEnterprise.setBackground(new java.awt.Color(0, 0, 0));
        btnManageEnterprise.setForeground(new java.awt.Color(255, 255, 255));
        btnManageEnterprise.setText("Manage Enterprises");
        btnManageEnterprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageEnterpriseActionPerformed(evt);
            }
        });
        add(btnManageEnterprise, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 330, 190, 30));

        btnCovid.setBackground(new java.awt.Color(0, 0, 0));
        btnCovid.setForeground(new java.awt.Color(255, 255, 255));
        btnCovid.setText("Covid Cases Chart");
        btnCovid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCovidActionPerformed(evt);
            }
        });
        add(btnCovid, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 580, 190, 30));

        btnManageEnterpriseAdmins.setBackground(new java.awt.Color(0, 0, 0));
        btnManageEnterpriseAdmins.setForeground(new java.awt.Color(255, 255, 255));
        btnManageEnterpriseAdmins.setText("Manage Enterprise Admins");
        btnManageEnterpriseAdmins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageEnterpriseAdminsActionPerformed(evt);
            }
        });
        add(btnManageEnterpriseAdmins, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 420, -1, 30));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("WELCOME, SYSTEM ADMIN");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 900, -1));

        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("View Covid Chart");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 620, -1, -1));

        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Create a New City");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 290, -1, -1));

        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Create a New Enterprise in City");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 370, -1, -1));

        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Create Admins of City Enterprise");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 460, -1, -1));

        jTree.setBackground(new java.awt.Color(94, 153, 211));
        jTree.setForeground(new java.awt.Color(0, 0, 0));
        jTree.setMinimumSize(new java.awt.Dimension(0, 860));
        jScrollPane1.setViewportView(jTree);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 860));

        btnManagePerson1.setBackground(new java.awt.Color(0, 0, 0));
        btnManagePerson1.setForeground(new java.awt.Color(255, 255, 255));
        btnManagePerson1.setText("Manage Person");
        btnManagePerson1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagePerson1ActionPerformed(evt);
            }
        });
        add(btnManagePerson1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 510, 190, 30));

        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Create Person ");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 550, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void createChart() {
        DefaultPieDataset dataset = new DefaultPieDataset();

        ArrayList<Person> personList = system.getPersonDirectory().getPersonList();
// System.out.println(personList);
        int positive = 0;
        int negative = 0;

        for (Person p : personList) {
//System.out.println(p.getTestHistory().getTestReportList());
            if (p.getTestHistory().getTestReportList().size() != 0) {
                if (p.getTestHistory().getTestReportList().get(0).isResult() == true) {
                    ++positive;
                }
                if (p.getTestHistory().getTestReportList().get(0).isResult() == false) {
                    ++negative;
                }
//System.out.println(positive);
//System.out.println(negative);
            }
        }
        if (negative == 0 && positive == 0) {
            JOptionPane.showMessageDialog(this, "No Data Found", "Warning", JOptionPane.INFORMATION_MESSAGE);
            return;
        } else {
            dataset.setValue("Positive", positive);
            dataset.setValue("Negative", negative);

            JFreeChart chart = ChartFactory.createPieChart3D(
                    "Covid Cases in City", // chart title
                    dataset, // data
                    true, // include legend
                    true,
                    false);
            final PiePlot3D plot = (PiePlot3D) chart.getPlot();
            plot.setStartAngle(270);
            plot.setForegroundAlpha(0.60f);
            plot.setInteriorGap(0.02);
            int width = 640;
            /* Width of the image */
            int height = 480;
            /* Height of the image */


            ChartFrame chartFrame = new ChartFrame("Chart", chart);
            chartFrame.setVisible(true);
            chartFrame.setSize(500, 500);
        }
    }

    private void btnCovidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCovidActionPerformed
        createChart();

    }//GEN-LAST:event_btnCovidActionPerformed

    private void btnManageEnterpriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageEnterpriseActionPerformed
        ManageEnterprisesJPanel manageTestCenterJPanel = new ManageEnterprisesJPanel(userProcessContainer, system);
        userProcessContainer.add("manageTestCenterJPanel", manageTestCenterJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageEnterpriseActionPerformed

    private void btnManageCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageCityActionPerformed
        ManageCityJPanel manageHospitalJPanel = new ManageCityJPanel(userProcessContainer, system);
        userProcessContainer.add("manageHospitalJPanel", manageHospitalJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageCityActionPerformed

    private void btnManageEnterpriseAdminsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageEnterpriseAdminsActionPerformed
        ManageEnterpriseAdminsJPanel manageVaccinationCenterJPanel = new ManageEnterpriseAdminsJPanel(userProcessContainer, system);
        userProcessContainer.add("manageVaccinationCenterJPanel", manageVaccinationCenterJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageEnterpriseAdminsActionPerformed

    private void btnManagePerson1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagePerson1ActionPerformed
        // TODO add your handling code here:
        ManagePersonJPanel managePersonJPanel = new ManagePersonJPanel(userProcessContainer, system);
        userProcessContainer.add("managePersonJPanel", managePersonJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        

    }//GEN-LAST:event_btnManagePerson1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCovid;
    private javax.swing.JButton btnManageCity;
    private javax.swing.JButton btnManageEnterprise;
    private javax.swing.JButton btnManageEnterpriseAdmins;
    private javax.swing.JButton btnManagePerson1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree;
    // End of variables declaration//GEN-END:variables
}
