/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Hospital;

import Business.City.City;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.Hospital;
import Business.Organization.Organization;
import Business.Patient.Patient;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.Order;
import Business.WorkQueue.VaccinatePatient;
import java.util.ArrayList;
import javax.swing.JPanel;

/**
 *
 * @author ayushgupta
 */
public class PlaceVaccinationRequest extends javax.swing.JPanel {

    /**
     * Creates new form PlaceVaccinationRequest
     */
    JPanel userProcessContainer;
    EcoSystem system;
    UserAccount userAccount;
    Organization organization;
    Enterprise enterprise;
    City city;
    public PlaceVaccinationRequest(JPanel userProcessContainer, City city, UserAccount userAccount, Organization organization, 
            Enterprise enterprise, EcoSystem system) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.system=system;  
        this.userAccount=userAccount;
        this.enterprise=enterprise;
        this.city=city;
        this.organization=organization;
        populateComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbVaccinationCenters = new javax.swing.JComboBox<>();
        btnSendRequest = new javax.swing.JButton();

        jLabel1.setText("Select Test Center");

        cmbVaccinationCenters.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnSendRequest.setText("Send Request");
        btnSendRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendRequestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(cmbVaccinationCenters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(btnSendRequest)))
                .addContainerGap(293, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbVaccinationCenters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(btnSendRequest)
                .addContainerGap(97, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendRequestActionPerformed
     //   String vaccineName;
    //int qty;
    String message = "Please Vaccinate";
    String status = "Active";
    
    //vaccineName = txtVaccineName.getText();
    //qty = Integer.parseInt(txtQty.getText());
    ArrayList<Patient> pd = new ArrayList<>();
    Hospital hospital = (Hospital)enterprise;
    for(Patient p : hospital.getPatientDirectory().getPatientDir()){
        if(!p.getVaccinationStatus().equals("Fully Vaccinated")){
            pd.add(p);
        }
    }
    String VaccineCenterName = (String) cmbVaccinationCenters.getSelectedItem();
    for(City city : system.getCityList()){
        for (Enterprise e : city.getEnterpriseDirectory().getEnterpriseList()) {
            if((e.getName()).equals(VaccineCenterName)){
                UserAccount receiver = e.getUserAccountDirectory().getUserAccountList().get(0);
                VaccinatePatient vp = e.getWorkQueue().addWorkRequestList2(message, userAccount, receiver, status);
                vp.setNonVaccPatientList(pd);
                //System.out.println(e.getWorkQueue().getWorkRequestList().get(0));
            }
            
        }
        }// TODO add your handling code here:
    }//GEN-LAST:event_btnSendRequestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSendRequest;
    private javax.swing.JComboBox<String> cmbVaccinationCenters;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
private void populateComboBox() {
        cmbVaccinationCenters.removeAllItems();
        for(City city : system.getCityList()){
        for (Enterprise e : city.getEnterpriseDirectory().getEnterpriseList()) {
            //System.out.println(e.getClass().getName());
            if((e.getClass().getName()).equals("Business.Enterprise.VaccinationCenter"))
            cmbVaccinationCenters.addItem(e.getName());
        } //To change body of generated methods, choose Tools | Templates.
    }
    }


}

