/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.VaccineManufacturer;

import Business.City.City;
import Business.DeliveryMan.DeliveryMan;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.Order;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ayushgupta
 */
public class AssignDeliveryManagerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AssignDeliveryManager
     */
    JPanel userProcessContainer;
    EcoSystem system;
    UserAccount userAccount;
    Organization organization;
    Enterprise enterprise;
    City city;
    Order order;
    public AssignDeliveryManagerJPanel(JPanel userProcessContainer, City city, UserAccount userAccount, Organization organization, 
            Enterprise enterprise, EcoSystem system, Order order) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.system=system;
        this.userAccount=userAccount;
        this.city=city;
        this.organization=organization;
        this.enterprise=enterprise;
        this.order=order;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDeliveryManager = new javax.swing.JTable();
        btnAssignOrder = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(167, 199, 231));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblDeliveryManager.setBackground(new java.awt.Color(214, 229, 244));
        tblDeliveryManager.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Delivery ManagerName", "ID"
            }
        ));
        jScrollPane1.setViewportView(tblDeliveryManager);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, 550, 160));

        btnAssignOrder.setBackground(new java.awt.Color(0, 0, 0));
        btnAssignOrder.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnAssignOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnAssignOrder.setText("Assign Order");
        btnAssignOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignOrderActionPerformed(evt);
            }
        });
        add(btnAssignOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 470, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, -1, -1));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ASSIGN DELIVERY");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 530, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignOrderActionPerformed
    int selectedRow = tblDeliveryManager.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null,"Please select a row from the table to view details","Warning",JOptionPane.WARNING_MESSAGE);
        }
        
        UserAccount deliveryManager  = (UserAccount) tblDeliveryManager.getValueAt(selectedRow, 0);
        
        for (WorkRequest wr : enterprise.getWorkQueue().getWorkRequestList()) {
                    Order order1 = (Order)wr;
                    if(order1.getId()==order.getId()){
                        order.setDeliveryManager(deliveryManager);
                    }
        }
    }//GEN-LAST:event_btnAssignOrderActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageOrdersJPanel manageOrderjp = (ManageOrdersJPanel) component;
        //        sysAdminwjp.populateTree();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssignOrder;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDeliveryManager;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel)tblDeliveryManager.getModel();
        
        model.setRowCount(0);
        
        for(UserAccount userAccount : enterprise.getUserAccountDirectory().getUserAccountList()){
            if((userAccount.getRole().getClass().getName()).equals("Business.Role.DeliveryManagerRole")){
               Object[] row = new Object[2];
               
                row[0] = userAccount;
                row[1] = userAccount.getEmployee().getId();
         
                
                model.addRow(row);
            }
        }//To change body of generated methods, choose Tools | Templates.
    }
}
